/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: GEARBOX_N                                             *
* Dimensions:  97 * 125                                              *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmGEARBOX_N;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsGEARBOX_N[] = {
  0x000000, 0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalGEARBOX_N = {
  2,  // Number of entries
  0,  // No transparency
  &_ColorsGEARBOX_N[0]
};

static GUI_CONST_STORAGE unsigned char _acGEARBOX_N[] = {
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, __XXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________, _______X, XXXXXXXX, X_______, ________,
  _______X, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, ________, ______XX, XXXXXXXX, XXX_____, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  ______XX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXXXX, X_______, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXXXX, XX______, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XX______, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXX_____, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXX_____, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ____XXXX, XXXXXXXX, XXXX____, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ____XXXX, XXXXXXXX, XXXXX___, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ____XXXX, XXXXXXXX, XXXXX___, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, _____XXX, XXXXXXXX, XXXXXX__, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ______XX, XXXXXXXX, XXXXXX__, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ______XX, XXXXXXXX, XXXXXXX_, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, _______X, XXXXXXXX, XXXXXXX_, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, _______X, XXXXXXXX, XXXXXXXX, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, _XXXXXXX, XXXXXXXX, X_______, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, _XXXXXXX, XXXXXXXX, XX______, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, __XXXXXX, XXXXXXXX, XXX_____, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ___XXXXX, XXXXXXXX, XXX_____, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ___XXXXX, XXXXXXXX, XXX_____, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ____XXXX, XXXXXXXX, XXXX____, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ____XXXX, XXXXXXXX, XXXXX___, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, _____XXX, XXXXXXXX, XXXXX___, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, _____XXX, XXXXXXXX, XXXXXX__, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ______XX, XXXXXXXX, XXXXXX__, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ______XX, XXXXXXXX, XXXXXXX_, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, _______X, XXXXXXXX, XXXXXXX_, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, XXXXXXXX, XXXXXXXX, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, _XXXXXXX, XXXXXXXX, X_______, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, _XXXXXXX, XXXXXXXX, XX______, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, __XXXXXX, XXXXXXXX, XX______, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, __XXXXXX, XXXXXXXX, XXX_____, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ___XXXXX, XXXXXXXX, XXX_____, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ___XXXXX, XXXXXXXX, XXXX____, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ____XXXX, XXXXXXXX, XXXXX___, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ____XXXX, XXXXXXXX, XXXXX___, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, _____XXX, XXXXXXXX, XXXXXX__, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ______XX, XXXXXXXX, XXXXXX__, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ______XX, XXXXXXXX, XXXXXX__, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, _______X, XXXXXXXX, XXXXXXX_, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, _______X, XXXXXXXX, XXXXXXXX, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, XXXXXXXX, XXXXXXXX, ________, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, _XXXXXXX, XXXXXXXX, X_______, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, __XXXXXX, XXXXXXXX, XX______, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, __XXXXXX, XXXXXXXX, XX______, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ___XXXXX, XXXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ___XXXXX, XXXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXX____, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ____XXXX, XXXXXXXX, XXXX____, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, _____XXX, XXXXXXXX, XXXXX___, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ______XX, XXXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ______XX, XXXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, _______X, XXXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XX______, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XX______, ________,
  ______XX, XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, X_______, ________,
  _______X, XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________, _____XXX, XXXXXXX_, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmGEARBOX_N = {
  97, // xSize
  125, // ySize
  13, // BytesPerLine
  1, // BitsPerPixel
  _acGEARBOX_N,  // Pointer to picture data (indices)
  &_PalGEARBOX_N   // Pointer to palette
};

/*************************** End of file ****************************/
