#ifndef DISPLAYCONSTANT_H
#define DISPLAYCONSTANT_H

// DISPLAY CONSTANTS

#define NUMBER_OF_SCREENS 6
#define STARTING_SCREEN 0

	// SCREEN NAMES
#define HOME 0
#define RACE 1
#define DRAG 2
#define ENDURANCE 3
#define SKIDPAD 4
#define SETUP 5

	// ALARMS CONSTANTS
#define ALARM_NOT_INTERRUPTABLE_TIME	4000 //ms
#define ALARM_BONUS_TIME				3000 //ms
#define ALARM_AUTOMATIC_TIMEOUT_TIME	60000 //ms
#define ALARM_DEACTIVATION_TIME			30000 //ms

	// TIME CONSTANTS
#define ANTI_FLICKER_TIME				300 //ms

	// SCREEN CONSTANTS
#define SCREEN_WIDTH	480
#define SCREEN_HEIGHT	272
#define START_SCREEN 0
#define SCREEN_NUMBERS 6
#define EMPTY_VALUE -1
#define FADE_MAX 255
#define FADE_MIN 127
#define SCREEN_DISABLED 255
#define ALARM_OFF 0
#define ALARM_ON 1
#define DISPLAY_FPS 30
#define PRESENTATION_DURATION 5
	//RPM
#define MIN_RPM			0
#define LOW_RPM_MAX		5500
#define MEDIUM_RPM		10500
#define MAX_RPM			12500

#endif /* DISPLAYCONSTANT_H */
