#pragma once

/* DataControls section */

#define BATTERY_VOLTAGE_CONVERSION_FACTOR			0.001f
#define LAUNCH_CONTROL_STATUS_CONVERSION_FACTOR		1.0f
#define PEDAL_CONVERSION_FACTOR						1.0f
#define BRAKE_CONVERSION_FACTOR						1.0f
#define BRAKE_REAR_CONVERSION_FACTOR				1.0f
#define TRACTION_CONTROL_CONVERSION_FACTOR			1.0f
#define STEER_CONVERSION_FACTOR						1.0f
#define LATITUDE_CONVERSION_FACTOR					0.0000001f
#define LONGITUDE_CONVERSION_FACTOR					0.0000001f
#define ALTITUDE_CONVERSION_FACTOR					0.01f

#define BATTERY_VOLTAGE_ALARM_PRIORITY 	0
#define BATTERY_VOLTAGE_MAX_VALUE		((float) 14)
#define BATTERY_VOLTAGE_MIN_VALUE		((float) 11.6)

#define TRACTION_REFRESH_TIME		10 //ms
#define TRACTION_OFF_UPPER_VALUE	500
#define TRACTION_1_UPPER_VALUE		1300
#define TRACTION_2_UPPER_VALUE		1900
#define TRACTION_3_UPPER_VALUE		2200
#define TRACTION_4_UPPER_VALUE		2500

/* DataMechanics section */

#define RPM_CONVERSION_FACTOR			1.0f
#define GEAR_CONVERSION_FACTOR			1.0f
#define SLIP_CONVERSION_FACTOR			1.0f
#define SPEED_CONVERSION_FACTOR			0.1f
#define TPS_CONVERSION_FACTOR			0.1f
#define CAR_HEIGHT_CONVERSION_FACTOR 	0.01f

#define RPM_MAX_VALUE				((float) 12500)

/* DataThermalPressure section */

#define OIL_PRESSURE_CONVERSION_FACTOR			0.001f
#define OIL_TEMPERATURE_CONVERSION_FACTOR		0.1f
#define FUEL_PRESSURE_CONVERSION_FACTOR			0.001f
#define FUEL_TEMPERATURE_CONVERSION_FACTOR		0.1f
#define AIR_TEMPERATURE_CONVERSION_FACTOR		0.1f
#define WATER_TEMPERATURE_CONVERSION_FACTOR		0.1f

#define OIL_PRESSURE_ALARM_PRIORITY				0
#define OIL_PRESSURE_MAX_VALUE					((float) 5)
#define OIL_PRESSURE_MIN_VALUE					((float) 1)
#define OIL_TEMPERATURE_ALARM_PRIORITY			1
#define OIL_TEMPERATURE_MAX_VALUE				((float) 135)
#define OIL_TEMPERATURE_MIN_VALUE				((float) 70)
#define FUEL_PRESSURE_ALARM_PRIORITY			2
#define FUEL_PRESSURE_MAX_VALUE					((float) 5)
#define FUEL_PRESSURE_MIN_VALUE					((float) 3.5)
#define FUEL_TEMPERATURE_ALARM_PRIORITY			2
#define FUEL_TEMPERATURE_MAX_VALUE				((float) 90)
#define FUEL_TEMPERATURE_MIN_VALUE				((float) 10)
#define AIR_TEMPERATURE_ALARM_PRIORITY			4
#define AIR_TEMPERATURE_MAX_VALUE				((float) 60)
#define AIR_TEMPERATURE_MIN_VALUE				((float) 5)
#define WATER_TEMPERATURE_ALARM_PRIORITY		0
#define WATER_TEMPERATURE_MAX_VALUE				((float)105)
#define WATER_TEMPERATURE_MIN_VALUE				((float) 60)